Traceback (most recent call last):
  File "C:/Users/bryne/Documents/GitHub/Python/PythonProjects/tracebackException.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
